### ISSUE TITLE
Generate from Query Plan

### ISSUE THREAD

**Issue by beeing** [sanpii/explain#9]
Hi @sanpii, thanks for such interesting project.

Does the CLI accept query plan text file, something similar to https://explain.depesz.com ?

For production environments, we may only obtain the query plan without direct database access.

Thanks.

**Comment by sanpii** [comment]
Hi,

Yes, this is what I use to generate examples:

```
explain --dry-run --file examples/plan_1.json --output examples/plan_1.dot
```
